language: node_js

go:
  - 1.7
node_js:
  - 6
env:
  GOPATH: ${TRAVIS_BUILD_DIR}/_workspace

before_install:
  - go version
  - eval "$(gimme 1.7)"
  - go version
  - mkdir $GOPATH
  - go get -u github.com/cozy/cozy-stack

# this is not a go repo, dont install nothing
install: true

before_script:
  - go version
  - nohup go run $GOPATH/src/github.com/cozy/cozy-stack/main.go

script:
  - npm --version
  - node --version
  - go version
  - curl http://localhost:8080/data/foo/bar
